### ISSUE TITLE
Update nodes to use docker from c4dt/byzcoin

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2248]
Update the following nodes to use the docker from https://github.com/c4dt/byzcoin and to update automatically at least once per week:
- [x] dedis.nella.org
- [x] 128.179.33.44 - EPFL cothority server
- [x] fairywren.ch
- [x] 188.166.35.173 - Node of the wookie

**Comment by nkcr** [comment]
In my case the generated config is different from the previous one, which produces "bad handshake" errors. Here is the diff on private.toml

```diff
diff backup_config/private.toml conode_data/private.toml 
8,11c8,11
< Description = "Wookiee's Cothority"
< URL = ""
< WebSocketTLSCertificate = ""
< WebSocketTLSCertificateKey = ""
---
> Description = "Node of a Wookiee"
> URL = "https://wookiee.ch/conode"
> WebSocketTLSCertificate = "/byzcoin/wookiee.ch.certificate.pem"
> WebSocketTLSCertificateKey = "/byzcoin/wookiee.ch.key.pem"
```

**Comment by ineiti** [comment]
Did you try with `USE_TLS=false` in docker-compose.yaml?

**Comment by nkcr** [comment]
> Did you try with USE_TLS=false in docker-compose.yaml?
Yes, tried both options with the same result.

**Comment by ineiti** [comment]
Can you post your `docker-compose.yaml`, please?

And what is your `docker images | grep c4dt/byzcoin | grep latest` output?

**Comment by nkcr** [comment]
My docker-compose.yml

```yml
version: "3.0"

services:
  byzcoin:
    environment:
      # ADDRESS_NODE should always be tls:// - tcp:// is insecure and should
      # not be used.
      - ADDRESS_NODE=tls://188.166.35.173:7770
      # ADDRESS_WS can be either http:// or https:// - for most of the use-cases
      # you want this to be https://, so that secure webpages can access the node.
      - ADDRESS_WS=https://wookiee.ch/conode
      # A short description of your node that will be visible to the outside.
      - DESCRIPTION=Node of a Wookiee
      # Whether to use TLS in the conodes. It is tested against 'false'. So
      # anything different from 'false' will be interpreted as true.
      - USE_TLS=false
      # WS_SSL_* is ignored if ADDRESS_WS is http or USE_TLS=false. These files 
      # need to be in the ~/byzcoin directory before the node is started.
      - WS_SSL_CHAIN=wookiee.ch.certificate.pem
      - WS_SSL_KEY=wookiee.ch.key.pem
      # ID of the byzcoin to follow - this corresponds to the DEDIS byzcoin.
      - BYZCOIN_ID=9cc36071ccb902a1de7e0d21a2c176d73894b1cf88ae4cc2ba4c95cd76f474f3
      # How much debugging output - 0 is none, 1 is important ones, 2 is
      # interesting, 3 is detailed, 4 is lots of details, and 5 is too detailed for
      # most purposes.
      - DEBUG_LVL=2
      # Whether to niceify the debug outputs. If you put this to `true`, you should
      # have a black background in the terminal.
      - DEBUG_COLOR=false
      # If set to true, adds a timestamp to each log-message
      - DEBUG_TIME=true
      # Send the logging information to a graylog instance. Optional, can be put to
      # "" if not needed.
      - GRAYLOG=
      # Send tracing information to honeycomb.io. The format is: api_key:dataset.
      # If no key is set, tracing is disabled.
      - HONEYCOMB_API_KEY=
    ports:
      - "7770-7771:7770-7771"
    image: c4dt/byzcoin:latest
    volumes:
      # Where the byzcoin data resides on the host. Do not change the :/byzcoin
      # part, only the ~/byzcoin.
      - ~/conode_data:/byzcoin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "4"
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --label-enable
```

Ok, `docker-compose pull; docker-compose down; docker-compose up` done!

Output of `docker images | grep c4dt/byzcoin | grep latest`:

```bash
c4dt/byzcoin            latest              88ce644832f8        14 hours ago        95.8MB
```

Now the only diff is the URL

```diff
diff backup_config/private.toml conode_data/private.toml 
8,9c8,9
< Description = "Wookiee's Cothority"
< URL = ""
---
> Description = "Node of a Wookiee"
> URL = "https://wookiee.ch/conode"
```

But it still doesn't work.
